server.port: 7000
server.error.include-message: always

app:
  product-service:
    host: localhost
    port: 7001

  recommendation-service:
    host: localhost
    port: 7002

  review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    ma.msa: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  product:
    host: product
    port: 8080

  recommendation:
    host: recommendation
    port: 8080

  review:
    host: review
    port: 8080